cccSite/Janitor/urls.py
from django.urls import path
from . import views

app_name = "Janitor"
urlpatterns = [
    path("", views.default, name="default"),
    path("messages/", views.contactList, name="messageList"),
    path("member/", views.memberList, name="memberList"),
    path("member/<int:want>/", views.member_manage, name="manage_user"),
    path("forum/", views.pendingForumList, name='forumList'),
    path('forum/<int:want>/', views.rev_forum, name='forumReview'),
    path('reports/', views.reportList, name="reportList"),
    path('tags/', views.tagList, name = "tagList"),
]

cccSite/boiler/urls.py
from django.urls import path
from . import views
#from mapViewer.views import viewMap

app_name = "boiler"
urlpatterns = [
   # path("", viewMap, name="viewMap"),
    path("about/", views.about, name="about"),
    path('help/', views.help, name='help'),
]

cccSite/cccSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mapViewer import views

app_name = 'mapViewer'

urlpatterns = [
    path("contribute/", include("account.urls")),
    path('DJadmin/', admin.site.urls),
    path("", include("mapViewer.urls")),
    path("", include("boiler.urls")),
    path("admin/", include("Janitor.urls")),
    path('forum/<int:want>/', views.forum_detail, name='forum_detail'),
] 
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

cccSite/Janitor/models.py
from django.db import models
from mapViewer.models import Forum
from account.models import Member

# Create your models here.
class ForumReport(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    reason = models.TextField()

class UserReport(models.Model):
    account = models.ForeignKey(Member, on_delete=models.CASCADE)
    reason = models.TextField()


    

cccSite/account/models.py
from django import forms
from django.db import models
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput, Textarea
from django.urls import reverse
from .storage import OverwriteStorage
from django.utils.translation import gettext_lazy as _


#function used for saving images
def user_directory_profile(instance, filename): 
    # file will be uploaded to MEDIA_ROOT / users / <pk> / profile.<ext>
    ext = filename.split('.')[-1]
    filename="profile."+ext
    return 'users/{0}/{1}'.format(instance.pk, filename) 

# user model. self explanitory
class Member(models.Model):
    name = models.CharField(max_length=35, )
    ranking_options = { 
        (-1,"banned"),
        (1 , "member"),
        (2 , "trusted member"),
        (98 , "moderator"),
        (99 , "admin"),
    }
    ranking = models.SmallIntegerField(default=1, choices=ranking_options)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    email = models.EmailField()
    pic = models.ImageField(upload_to=user_directory_profile, storage = OverwriteStorage(), default='default/blankprof.png')
    about = models.TextField(blank=True, default="")

   #location
    def __str__(self):
        return self.name
    @property
    def get_absolute_url(self):
        return reverse("account:account_view", args=[str(self.pk)])
    @property
    def get_admin_url(self):
        return reverse("Janitor:manage_user", args=[str(self.pk)])
    #https://stackoverflow.com/questions/3715103/password-field-in-django-model/3715382#3715382 for making own password


# when user logs in with google, check the given google ID against this and then authenticate as user that is pointed to
# same pattern can be used to implement other log in methods
class GLogIn(models.Model):
    googleID = models.CharField(max_length=255, unique=True)
    referTo = models.ForeignKey(Member, on_delete = models.CASCADE)
    def __str__(self):
        return self.googleID + "|" + str(self.referTo)

class ManageForm(ModelForm):
    class Meta:
        model = Member
        fields = ["pic", "name", "email", "about"]

        widgets = {
            
            'name': forms.TextInput(attrs={'class':'nameField'}),
            'email':forms.EmailInput(attrs={'class':'emailField'}),
            'about': forms.TextInput(attrs={'class':'aboutField'})
        }
        
class AccountCreation(models.Model):    
    email = models.EmailField()
    username = models.CharField(max_length=75)
    displayname = models.CharField(max_length=75)
    password = models.CharField(max_length=50)
    confirmpassword = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    
    def __str__(self):
        return self.email + " | " + self.username + " | " + self.displayname
    
class MessageForm(ModelForm):
    class Meta:
        model = AccountCreation
        fields = ['email', 'username', 'displayname', 'password', 'confirmpassword']
        labels = {
            "email": _("Email"),
            "username": _("Username"),
            "displayname": _("Displayname"),
            
        }
        widgets = {
            'email': EmailInput(attrs={'placeholder': 'Email address', 'class': 'input-text'}),
            'username': TextInput(attrs={'placeholder': 'Username', 'class': 'input-text'}),
            'displayname': TextInput(attrs={'placeholder': 'Displayname', 'class': 'input-text'}),
            'password': PasswordInput(attrs={'placeholder': 'Password', 'class': 'input-text'}),
            'confirmpassword': PasswordInput(attrs={'placeholder': 'Password', 'class': 'input-text'}),
        }

cccSite/Janitor/forms.py
from django.forms import Form, ModelForm
from django import forms
from account.models import Member
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from mapViewer.models import Tag, Forum
from .models import *

class TagRemover(Form):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, label="Tags")

class TagAdder(ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

class UserRepForm(ModelForm):
    class Meta:
        model = UserReport
        fields = ['reason', 'account']
        widgets = {
            'account' : forms.HiddenInput,
        }

class ForumRepForm(ModelForm):
    class Meta:
        model = ForumReport
        fields = ['reason', 'forum']
        widgets = {
            'forum' : forms.HiddenInput,
        }

class ForumManager(ModelForm):
    reason = forms.CharField(label="Reason", widget=forms.Textarea, required=False)
    

    class Meta:
        model = Forum
        fields = ['visibility', 'description']
        
        widgets={
            'description' : forms.HiddenInput,
        }
        
    def clean(self): 
        cleaned_data = super().clean() #verify that all the other fields are ok
        if cleaned_data.get('visibility')==-1: #if visibility has been set to blocked
            if not cleaned_data.get('reason'): #make sure a reason was provided
                raise ValidationError(_("You must include a reason."), code="reaserr")
            else: #if it was provided, set the description to the reason so the user knows.
                cleaned_data = {'reason' : cleaned_data.get('reason'),
                                'visibility' : cleaned_data.get('visibility'),
                                'description' : cleaned_data.get('reason')}
        return cleaned_data
        
    def _clean_form(self): #when we check is_valid, this occurs
        try:
            cleaned_data = self.clean() #try to clean the data
        except ValidationError as e:
            match e.code:
                case "reaserr":
                    self.add_error('reason', e)
        else:
            if cleaned_data is not None:
                self.cleaned_data = cleaned_data #if successful, store in cleaned_data
    
    

class MemberManager(ModelForm):
    class Meta:
        model = Member
        #! fields = ['name', 'ranking', 'email','pic','about']
        fields = ['ranking', 'pic','about']

cccSite/Janitor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from boiler.models import Message
from account.models import Member
from .models import ForumReport, UserReport
from mapViewer.models import Forum, Tag, Media
from .forms import *
from django.db.models import Count

# Create your views here.
def default(request):
    databaseRank = Member.objects.get(pk=request.session.get('user',-1)).ranking
    if request.session.get('rank',0) != databaseRank:
        request.session['rank']=databaseRank
    return render(request, "Janitor/AdminBase.html")

#displays a list of accordion elements that show contact instances from the contact us form.
def contactList(request):
    messages = Message.objects.all() #fetch messages
    return render(request, "Janitor/contactList.html", {'messages' : messages,})#pass messages to template

#display a list of users, not including the currently logged in account. needs to be remade using querysets to allow searching/sorting
def memberList(request):
    if request.session.get('rank',0) != 99: #if user isn't an admin, they aren't allowed to edit ranks
        redirect(default)
    members = Member.objects.exclude(pk=request.session.get('user',-1)) #exclude the actively logged in user, so admins can't edit their own rank
    memberStats = [] #list for storing a dictionary that associates a user object with their stats
    for user in members:
        visibleforums = Forum.objects.filter(author=user, visibility__gt=0).count() #number of forums that the user has made that were approved
        reports = ForumReport.objects.filter(forum__author=user).count()+UserReport.objects.filter(account=user).count() #number of reports against a user and their forums
        memberStats.append({'user' : user, 'goodforums': visibleforums, 'reports':reports}) #add to the stats list
    
    return render(request, "Janitor/memberList.html", {'members' : memberStats,}) #pass the list to the template

def member_manage(request, want): #view for adjusting user ranks and information
    if request.session.get('rank',0) != 99: #if the session isn't an admin
        redirect(default)
    if Member.objects.filter(pk=want).exists(): #confirm that the url corresponds to a user
        userInz=Member.objects.get(pk=want) #if so, get the relevant user object
    else:
        return redirect(memberList)
    if request.method == 'POST': #if method is post, a form has been submitted to edit the user's info
        form = MemberManager(request.POST, instance=userInz) 
        if form.is_valid:
            form.save()
    else:
        form = MemberManager(instance=userInz) #initalize form if request method was GET
    return render(request, 'Janitor/memberManager.html', {'form' : form,
                                                          })

def pendingForumList(request): #show a list of forums pending approval
    msg = ""
    forums= Forum.objects.filter(visibility=0) #fetch all forums with pending visibility
    if not forums:
        msg = "No pending forums!"
    return render(request, 'Janitor/forumList.html', {'forums' : forums,
                                                     'msg' : msg})

#view that allows the viewing of a forum with a form that allows admin/moderator to change visibility. 
def rev_forum(request, want): 
    msg="" #default value for msg is None, allows us to check if msg in template to decide whether to render msg or not
    if Forum.objects.filter(pk=want).exists(): #confirm forum object exists
        forumInz = Forum.objects.get(pk=want) #get forum and associated files form the database
        files = Media.objects.filter(forum=forumInz)
        if request.method == "POST": #if the method was POST, visibility has been updated
            form = ForumManager(request.POST, instance=forumInz) #forum manager is a modelform with custom form validation, see forms.py
            if form.is_valid(): #if form input is OK
                form.save()
                if form.cleaned_data['visibility'] == 1: #change msg so admin can confirm their change has been made
                    msg="Forum Approved!"
                elif form.cleaned_data['visibility'] == 0:
                    msg="No changes made."
                else:
                    msg="Forum Denied!"
        else:
            form = ForumManager(instance=forumInz)
        return render(request, 'Janitor/forumManager.html', {'form' : form,
                                                            'forum' : forumInz,
                                                            'files' : files,
                                                            'msg' : msg})
    return redirect(pendingForumList) #if the url doesn't correspond to a forum, redirect to the pending forum list

def tagList(request): #view allowing mod/admin to add/remove tags to the forum tagging system
    msg = ""
    if request.method == "POST":
        if 'addTag' in request.POST: #if a form has been posted, a tag is being added or deleted this checks which one, indicated by a hidden field
            addForm = TagAdder(request.POST)
            delForm = TagRemover()
            if addForm.is_valid(): 
                addForm.save()
                msg = addForm.cleaned_data['name'] + " has been successfully added."
                addForm = TagAdder()
        elif 'delTag' in request.POST:
            addForm = TagAdder()
            delForm = TagRemover(request.POST)
            if delForm.is_valid():
                for tag in delForm.cleaned_data['tags']:
                    tag.delete()
                msg = "Tag(s) successfully deleted."
    else:
        addForm = TagAdder()
        delForm = TagRemover()
    return render(request, "Janitor/tagList.html", {
        'msg' : msg,
        'addForm' : addForm,
        'delForm' : delForm,
    })

def exportData(request): #low priority
    #https://docs.djangoproject.com/en/5.0/howto/outputting-csv/
    return HttpResponse("Not implemented yet")

def reportList(request): #view for seeing reported forums/users and the reports associated with them
    msg=""
    if request.method == "POST": #if POST, there was an attempt to clear reports
        if request.POST.get('type') == 'user': #if the clear was from a user reports section
            userInz = Member.objects.get(pk=request.POST.get('pk')) #get user object
            msg=userInz.name + "'s reports have been cleared." #set the message
            UserReport.objects.filter(account=userInz).delete() #delete reports associated with user
        else: #same flow, but for forums
            forumInz = Forum.objects.get(pk=request.POST.get('pk'))
            msg=forumInz.title + "'s reports have been cleared."
            ForumReport.objects.filter(forum=forumInz).delete()
    #annotations essentially add a temporary field to model objects. in this case, we are adding the number of associated reports and sorting by it
    pwReports = Forum.objects.filter(forumreport__id__gt=0).distinct().annotate(num_reports=Count("forumreport")).order_by('-num_reports')
    uwReports = Member.objects.filter(userreport__id__gt=0).distinct().annotate(num_reports=Count("userreport")).order_by('-num_reports')
    #we create pList for forums, uList for users. each entry is a list, index 0= user/forum object and index 1= query set of reports associated with object
    pList = []
    uList = []
    for item in pwReports:
        reports = ForumReport.objects.filter(forum=item)
        tempList = [item,reports]
        pList.append(tempList)
    for item in uwReports:
        reports = UserReport.objects.filter(account=item)
        tempList = [item,reports]
        uList.append(tempList)
    #print(uList)
    return render(request, 'Janitor/reportList.html', {
        'msg' : msg,
        'pList' : pList,
        'uList' : uList,
    })

cccSite/Janitor/templates/Janitor/AdminBase.html
{%extends "base/base.html"%}
{%block head%}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Janitor/accordian.css' %}">
<title>Chesapeake Community Connect - Admin</title>
{%endblock head%}
{% block content %}
<div class="body">  
  {%if rank > 2%}
  <nav role="navigation" aria-label="Admin Navigation">
    <ul style="position:fixed;width: 15%;">
        <li><a class="button_CCC" href="{%url 'Janitor:forumList' %}" aria-label="Approve Forms">Approve Forums</a></li>
        <li><a class="button_CCC" href="{%url 'Janitor:tagList' %}" aria-label="Manage Tags">Manage Tags</a></li>
        <li><a class="button_CCC" href="{% url 'Janitor:reportList' %}" aria-label="View Reports">Reports</a></li>
        <li><a class="button_CCC" href="{% url 'Janitor:messageList'%}" aria-label="View Contact Requests">Contact Requests</a></li>
        {%if rank == 99%}<li><a class="button_CCC" href="{% url 'Janitor:memberList'%}" aria-label="Manage Users">Manage Users</a></li>{%endif%}
        <li><a class="button_CCC" href="#about" aria-label="Export Data">Export Data</a></li>
    </ul>
  {%endif%}
  {%if rank > 2%}
  <div style="margin-left:15%;padding:1px 16px;">
    {%block adminFunc%} Welcome to the admin interface. {% endblock adminFunc %}
  </div>
  {%else%}
    You do not have permission to access this page.
  {%endif%}
</div>
<script>
  // Script for smooth accordions
  var acc = document.getElementsByClassName("accordion");
  var i;
  for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function () {
          this.classList.toggle("active");
          var panel = this.nextElementSibling;
          if (panel.style.maxHeight) {
              panel.style.maxHeight = null;
          } else {
              panel.style.maxHeight = panel.scrollHeight + "px";
          }
      });
  }

</script>
{% endblock content %}

cccSite/Janitor/templates/Janitor/contactList.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
{%for item in messages %}
<button class="accordion">{{item.created}} - {{item.subject}} from {{item.sender}} | {{item.email}}</button>
<div class="panel">
    <p>{{item.message}}</p>
</div>
{%endfor%}
{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/forumList.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
{%if msg%}
{{msg}}
{%endif%}
{%for item in forums %}
<button class="accordion">{{item.title}} | {{item.description}} by {{item.author.name}}</button>
<div class="panel">
    <p><a class="button_CCC" href="{{item.get_absolute_url}}">View Forum</a><a class="button_CCC" href="{{item.get_admin_url}}">Manage Forum</a></p>
</div>
{%endfor%}
{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/forumManager.html
{% extends "Janitor/AdminBase.html" %}
{% load static %}

{% block adminFunc %}
<link rel="stylesheet" type="text/css" href="{% static 'mapViewer/viewforum.css' %}">
<script src="{% static 'mapViewer/forumview.js' %}" defer></script>
{{forum.geoCode|json_script}}
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBKcBxdWnx-AIYQfA-NQKUR1cRXeF9fAiI&libraries=places&callback=initMap" defer></script>

{%if msg%}
<br>{{msg}}<br>
{%endif%}
<br>
<div id="content" class="body">
    <form action="{{request.build_absolute_uri}}"  method="post">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save" id="input-submit">
    </form>
    
    <h1>{{forum.title}}</h1>
    <br>
    By {{forum.author}}
    <br>
    <!-- Slideshow HTML -->
    <div class="slideshow-container">
        <!-- Slides -->
        <div class="mySlides fade">
            <div id="map"></div>
        </div>
        {% for item in files %}
        <div class="mySlides fade">
            <div class="image-container">
                {% if item.format == 0 %}
                <img src="{{ item.file.url }}" class="slide-image">
                {% elif item.format == 1 %}
                <video width="100%" controls>
                    <source src="{{ item.file.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                {% elif item.format == 2 %}
                <audio controls>
                    <source src="{{ item.file.url }}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        
        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    <div id="caption">
    
    </div>
    {{forum.content}}
    <br>
    Tags:
    <br>
    {%for item in forum.tags.all %}
    {{item.name}}
    <br>
    {%endfor%}
    
</div>

{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/memberList.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
{%for item in members %}
<button class="accordion">{{item.user.name}} ({{item.user.email}}) - Rank: {{item.user.get_ranking_display}} - Visible Forums: {{item.goodforums}} - Reports: {{item.reports}}</button>
<div class="panel">
    <p><a class="button_CCC" href="{{item.user.get_absolute_url}}">View User</a><a class="button_CCC" href="{{item.user.get_admin_url}}">Manage User</a></p>
</div>
{%endfor%}
{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/memberManager.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
<div id="content">
    <form action="{{request.path}}" id="contact-form" method="post" enctype="multipart/form-data">
        {%csrf_token%}
         {{form.as_p}}
        <input class="submitB" type="submit" value="Save">
    </form>
</div>
{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/reportList.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
{{msg}}<br>
Forum Reports <br>
{%if pList%}
{%for entry in pList %}
<button class="accordion">{{entry.0.title}} - {{entry.0.num_reports}} Reports <form action="{%url 'Janitor:reportList' %}" method="post">{%csrf_token%}
    <input type="hidden" name= "type" value="post">
    <input type="hidden" name= "pk" value="{{entry.0.pk}}">
    <input type="submit" value="Clear Reports">
</form></button>
<div class="panel">
    {%for item in entry.1%}
    <p>{{item.reason}}</p>
    {%endfor%}
    <a class="button_CCC" href="{{entry.0.get_admin_url}}">Manage Forum</a>
</div>
{%endfor%}
{%else%}
No reports!
{%endif%}
<br>User Reports <br>
{%if uList%}
{%for entry in uList %}
<button class="accordion">{{entry.0.name}} - {{entry.0.num_reports}} Reports <form action="{%url 'Janitor:reportList' %}" method="post">{%csrf_token%}
    <input type="hidden" name= "type" value="user">
    <input type="hidden" name= "pk" value="{{entry.0.pk}}">
    <input type="submit" value="Clear Reports">
</form></button> 

<div class="panel">
    {%for item in entry.1%}
        <p>{{item.reason}}</p>
    {%endfor%}
    <a class="button_CCC" href="{{entry.0.get_admin_url}}">Manage User</a>
    </div>
</div>
{%endfor%}
{%else%}
No reports!
{%endif%}

{% endblock adminFunc %}

cccSite/Janitor/templates/Janitor/tagList.html
{%extends "Janitor/AdminBase.html"%}

{% block adminFunc %}
{{msg}}
<form action="{% url 'Janitor:tagList'%}"  method="post" aria-labelledby="add-tag-form" role="form">
    {% csrf_token %}
    {{addForm.as_p}}
    <input type="hidden" name= "addTag" value="">
    <input type="submit" value="Add Tag" aria-label="Add new tag">
</form>
<form action="{% url 'Janitor:tagList'%}"  method="post" aria-labelledby="delete-tag-form" role="form">
    {% csrf_token %}
    {{delForm.as_p}}
    <input type="hidden" name= "delTag" value="">
    <input type="submit" value="Delete Selected" aria-label="Delete selected tag">
</form>
{% endblock adminFunc %}