cccSite/boiler/urls.py
from django.urls import path
from . import views
#from mapViewer.views import viewMap

app_name = "boiler"
urlpatterns = [
   # path("", viewMap, name="viewMap"),
    path("about/", views.about, name="about"),
    path('help/', views.help, name='help'),
]

cccSite/cccSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mapViewer import views

app_name = 'mapViewer'

urlpatterns = [
    path("contribute/", include("account.urls")),
    path('DJadmin/', admin.site.urls),
    path("", include("mapViewer.urls")),
    path("", include("boiler.urls")),
    path("admin/", include("Janitor.urls")),
    path('forum/<int:want>/', views.forum_detail, name='forum_detail'),
] 
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

cccSite/mapViewer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "mapViewer"

urlpatterns = [
    path("", views.viewMap, name="default"),
    path("search/", views.forum_list, name="forum_list"),
    #path("forum/<int:want>/<int:page_number>/", views.forum_detail, name="forum_detail"),
    path("forum/<int:want>/", views.forum_detail, name="forum_detail"),    
    path("forum/<int:want>/post/<int:wants>/", views.post_detail, name="post_detail"),
    path("forum/<int:want>/post/<int:wants>/comment/", views.create_comment, name="create_comment"),
    # Add other URL patterns here
]

cccSite/mapViewer/models.py
from django.db import models
from account.models import Member
from django.urls import reverse
from uuid import uuid4
import magic



def tag_directory_profile(instance, filename): 
    # file will be uploaded to MEDIA_ROOT / users / <pk> / profile.<ext>
    ext = filename.split('.')[-1]
    filename="tag."+ext
    return 'title/{0}/{1}'.format(instance.pk, filename) 
class Tag(models.Model):
    name = models.CharField(max_length=25, unique=True)
    image = models.ImageField(upload_to=tag_directory_profile, blank=True, null=True, default='default/blankprof.png')
    def __str__(self):
        return self.name

# this will be the ideal forum model. we would serialize this to widgets using djangos JSON serialize functionality on the specific fields
class Forum(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    
    author = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL, related_name="forums")
    
    description = models.TextField()
    geoCode = models.JSONField()
    tags = models.ManyToManyField(Tag, related_name="forums", blank=True)
    
    
    visible_options = { 
        (-1,"denied"),
        (0, "pending"),
        (1 , "visible"),
    }
    visibility = models.SmallIntegerField(default=0, choices=visible_options)
    
    
    associated_choices = [
        ("associated", "I am associated with the group providing this solution"),
        ("not-associated", "I am not associated with the group providing this solution")
    ]
    associated = models.CharField(choices=associated_choices, max_length=150)
    
    private_public_choices = [
        ("public", "Public (Anyone can view and add Posts)"),
        ("private", "Private (Only invited Contributors can view and add Posts)")
    ]
    private_public = models.CharField(choices=private_public_choices, max_length=80)
    
    contributors = models.ManyToManyField(Member, related_name="contributed_forums", blank=True)
    
    def __str__(self):
        return self.title + " by " + str(self.author)
    @property
    def get_absolute_url(self):
        return reverse("mapViewer:forum_detail", args=[str(self.pk)])
    @property
    def get_admin_url(self):
        return reverse("Janitor:forumReview", args=[str(self.pk)])
    
    #https://forum.djangoproject.com/t/url-template-tag-get-absolute-url-and-views/21249
    #https://levelup.gitconnected.com/django-quick-tips-get-absolute-url-1c22321f806b

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    description = models.TextField()
    author = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL, related_name="posts")
    
    forum = models.ForeignKey(Forum, null=True, on_delete=models.SET_NULL, related_name="posts")
    

class Comment(models.Model):
    content = models.TextField()
    
    author = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL, related_name="comments")
    
    post = models.ForeignKey(Post, null=True, on_delete=models.SET_NULL, related_name="comments")
    
class Reply(Comment):
    
    parent = models.ForeignKey(Comment, null=True, on_delete=models.SET_NULL, related_name="children")
    # It's not really a recipient. It's just the Reply object this Reply object is replying to. I can't think of a better word.
    recipient = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, related_name="replies")
    
    
    

def media_directory(instance, filename): 
    # file will be uploaded to MEDIA_ROOT / forums / <forum.pk> / <pk>.<ext>
    ext = filename.split('.')[-1]
    filename="{0}.".format(uuid4().hex)+ext
    return 'forums/{0}/{1}'.format(instance.forum.pk, filename) 

class Media(models.Model):
    
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    
    format_options = { 
        (0, "image"),
        (1, "video"),
        (2 , "audio"),
    }
    format = models.SmallIntegerField(default=0, choices=format_options)
    file = models.FileField(upload_to=media_directory)
    def get_format(self):
        filetype = magic.from_buffer(self.file.read(), mime=True).split('/')[0]
        match filetype:
            case "image":
                return 0
            case "video":
                return 1
            case "audio":
                return 2
            

cccSite/mapViewer/forms.py
#https://medium.com/swlh/django-forms-for-many-to-many-fields-d977dec4b024
from django import forms
from django.conf import settings
from .models import Tag
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import googlemaps
from django.db import models
from datetime import datetime
import magic


class SearchForumsForm(forms.Form):
    q = forms.CharField(max_length=100, required=False, widget=forms.TextInput({"Placeholder": "Search..."}))
    t = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    class Meta:
        labels = {
                'q': _('Search'),
                't': _('Tags')
            }



#forum creation form
class MakeForumForm(forms.Form):
    def get_upload_attrs():#function that converts the list of accepted file types to a string for use in restricting what is selectable in the upload interface
        val = '' #start blank
        for item in settings.VALID_UPLOAD_TYPES: #for valid file type
            val = '{0},{1}'.format(val, item) #add to string
        return val
    def validate_file(value): #validator that verifies that uploaded file is of an accepted type. if not, raise validation error
        if magic.from_buffer(value.read(), mime=True) not in settings.VALID_UPLOAD_TYPES:
                raise ValidationError(_("Bad file"), code="filerr")


    title = forms.CharField(max_length=100, label="Title", widget=forms.TextInput({"Placeholder": "Title"})) #title of forum
    firstName = forms.CharField(max_length=100, label="First", widget=forms.TextInput({"Placeholder": "First"})) #first name of author of forum
    lastName = forms.CharField(max_length=100, label="Last", widget=forms.TextInput({"Placeholder": "Last"})) #last name of author of forum
    location = forms.CharField(max_length=200, label="Address", widget=forms.TextInput({"Placeholder": "Location"})) #location of forum as an address
    content = forms.CharField(label="Content", widget=forms.Textarea({"Placeholder": "Content"})) #content of the forum
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, label="Tags", required = False)#tags of forum
    geoResult = forms.JSONField(widget=forms.HiddenInput, required=False)#hidden field for converting from user provided address to google's geocode
    description = forms.CharField(label="Description", widget=forms.Textarea({"Placeholder": "Provide a brief description"}), required=True) # description of the forum  

    associated_choices = [
        ("associated", "I am associated with the group providing this solution"),
        ("not-associated", "I am not associated with the group providing this solution")
    ]
    associated = forms.ChoiceField(choices=associated_choices)
    
    private_public_choices = [
        ("public", "Public (Anyone can view and add Posts)"),
        ("private", "Private (Only invited Contributors can view and add Posts)")
    ]
    private_public = forms.ChoiceField(choices=private_public_choices)
    
    
    #the file upload fields. validated using the custom validator above, if left empty or if a bad file is submitted, these fields have nothing in them
    file1 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file2 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file3 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file4 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    

    

    
    #to minimize API calls, we don't want to geocode a provided address more than once. 
    #so if an address is correct, we want to use one geocode call to get the lat/long, but we can't just pass this to the model,
    #because if the provided address doesn't result in a valid geocode, we can't try to access said geocode. this stores a valid geocode
    #in the geoResult field of the form, and  also builds in an error message to the address code if there is no geocode
    def clean(self): 
        gmaps = googlemaps.Client(key='AIzaSyAH_5F4XRcZh8_OZib8cUD-DoE7ust60lc') #initialize maps
        cleaned_data = super().clean() #verify that all the other fields are ok
        if not cleaned_data['geoResult']: #if we don't have a geocode (first try or last try was invalid)
            geoResult=gmaps.geocode(address=self.cleaned_data['location']) #fetch geocode for provided address (API call)
            if not geoResult: #if still none, then the address is invalid
                raise ValidationError(_("Invalid Address"), code="adderr")
        #print(geoResult)
        return {'title': cleaned_data['title'],
                'firstName': cleaned_data['firstName'],
                'lastName': cleaned_data['lastName'],
                'location': cleaned_data['location'],
                'content': cleaned_data['content'],
                'tags': cleaned_data['tags'],
                'geoResult': geoResult,
                'description': cleaned_data['description'], 
                'associated': cleaned_data['associated'],
                'private_public': cleaned_data['private_public'],
                'files': [cleaned_data.get('file1'),cleaned_data.get('file2'),cleaned_data.get('file3'),cleaned_data.get('file4')],
                }  # if a file is legit, the .get returns the file. if not (or if it doesn't exist), 
                # the .get returns None, and so we can iterate through cleaned_data['files'] in a view, and check if an entry isn't None to 
                # see if we have a file to save or not
        
    def _clean_form(self): #when we check is_valid, this occurs
        try:
            cleaned_data = self.clean() #try to clean the data
        except ValidationError as e:
            match e.code:
                case "adderr":
                    self.add_error('location', e) #if we get the error of invalid address, attach it to the location field
                case "filerr":
                    self.add_error('file1', e) #if we get a file error, attach it to the first file field.
            
        else:
            if cleaned_data is not None:
                self.cleaned_data = cleaned_data #if successful, store in cleaned_data



class SearchPostsForm(forms.Form):
    q = forms.CharField(max_length=100, required=False, widget=forms.TextInput({"Placeholder": "Search..."}))
    t = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    class Meta:
        labels = {
                'q': _('Search'),
                't': _('Tags')
            }




class MakePostForm(forms.Form):
    def get_upload_attrs():#function that converts the list of accepted file types to a string for use in restricting what is selectable in the upload interface
        val = '' #start blank
        for item in settings.VALID_UPLOAD_TYPES: #for valid file type
            val = '{0},{1}'.format(val, item) #add to string
        return val
    def validate_file(value): #validator that verifies that uploaded file is of an accepted type. if not, raise validation error
        if magic.from_buffer(value.read(), mime=True) not in settings.VALID_UPLOAD_TYPES:
                raise ValidationError(_("Bad file"), code="filerr")


    title = forms.CharField(max_length=100, label="Title", widget=forms.TextInput({"Placeholder": "Title"})) #title of forum
    firstName = forms.CharField(max_length=100, label="First", widget=forms.TextInput({"Placeholder": "First"})) #first name of author of forum
    lastName = forms.CharField(max_length=100, label="Last", widget=forms.TextInput({"Placeholder": "Last"})) #last name of author of forum
    location = forms.CharField(max_length=200, label="Address", widget=forms.TextInput({"Placeholder": "Location"})) #location of forum as an address
    content = forms.CharField(label="Content", widget=forms.Textarea({"Placeholder": "Content"})) #content of the forum
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, label="Tags", required = False)#tags of forum
    geoResult = forms.JSONField(widget=forms.HiddenInput, required=False)#hidden field for converting from user provided address to google's geocode
    description = forms.CharField(label="Description", widget=forms.Textarea({"Placeholder": "Provide a brief description"}), required=True) # description of the forum
    associated_choices = [
        ("associated", "I am associated with the group providing this solution"),
        ("not-associated", "I am not associated with the group providing this solution")
    ]
    associated = forms.ChoiceField(choices=associated_choices)
    
    private_public_choices = [
        ("public", "Public (Anyone can view and add Posts)"),
        ("private", "Private (Only invited Contributors can view and add Posts)")
    ]
    private_public = forms.ChoiceField(choices=private_public_choices)
    
    
    #the file upload fields. validated using the custom validator above, if left empty or if a bad file is submitted, these fields have nothing in them
    file1 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file2 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file3 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])
    file4 = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept':get_upload_attrs()}), required=False, validators=[validate_file])

cccSite/mapViewer/templates/mapViewer/commentTemplate.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">

</head>
<body>
    <ul class="comment-list">
        <li class="comment-item">
            <p class="comment-author">@{{ comment.author }}</p>
            <div class="comment-content">
                {{ comment.content }}
                
            </div>
        </li>
        <!-- Repeat for other posts -->
    </ul>
</body>
</html>

cccSite/mapViewer/templates/mapViewer/create_post.html
{%extends "account/accountBase.html"%}

{% block accountFunc %}

<!--loads the form with line breaks between entries. posts to the URL titled manage in the account app's URL config-->
<div id="content">
    <div class="container">
        <form action="{% url 'mapViewer:post_create'%}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
    
            <input class="submitB" type="submit" value="Submit">
        </form>
    </div>
  
</div>
{% endblock accountFunc %}

cccSite/mapViewer/templates/mapViewer/forum_form.html
<!--TODO: Comment-->

{% load static %}

    <div class="body">
        <form action="{% url 'mapViewer:default'%}"  method="post">
            {% csrf_token %}
            {{forumForm.as_p}}
            <input type="submit" value="Submit" id="input-submit">
        </form>
    </div>
    

cccSite/mapViewer/templates/mapViewer/listForums.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
<title>Chesapeake Community Connect - Map</title>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBic0-t_tjjX9CnTFIZY2PdJPOF5hFhuQY&libraries=places"></script>
{% endblock head %}

{% block content %}
<div id="content" class="body">
    <h1>Chesapeake Community Connect</h1>
    <form action="{% url 'mapViewer:forum_list' %}" id="contact-form" method="get">
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
    {%for forum in forumList %}
    <ul>                         
        <li><a href="{% url 'mapViewer:forum_detail' want=forum.id %}">{{ forum.title }}</a>
         </li>                      
     </ul> 
    {%endfor%}
    
</div>

<footer class = "column is-full">
    {%block footer%}
    {%endblock footer%}
</footer>

{% endblock content %}

cccSite/mapViewer/templates/mapViewer/mapPage.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'mapViewer/mappagestyle.css' %}">
<title>Chesapeake Community Connect - Map</title>

<!--the defer guarantees that TEST
    a) the HTML loads pre JS execution so elements referenced in the script exist
    b) the API script is executed AFTER our script file is loaded and so the callback function works
    c) the widgets are rendered such that our script file can access them
-->
<script src="{% static 'mapViewer/map-script.js' %}" defer></script>
{{widgets|json_script}}
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBN4e1y8ECEgsg_8U6xO02_2InU8G8I8cM&libraries=places&callback=initMap" defer></script>

{% endblock head %}

{% block content %}
<div style="text-align: center; width: 100%; margin-bottom: 10px;">
    <p style="display: inline-block; max-width: 1000px; margin: 0 auto;">
        Use the interactive map below to explore community organizations and services in the Chesapeake area. 
        Zoom in or out to browse locations, and click any marker to view details about that organization. 
        You can also use the search panel on the right to filter results by name or category.
    </p>
</div>
    <!-- Map Section -->
    <div id="left">
        <div id="map"></div>
    </div>

    <div id="search">
        <form action="{% url 'mapViewer:default' %}" id="contact-form" method="get">
            {{ searchForm.q }}
            <div id="scroll-box">
                <div id="id_t">
                    {% for mTag in searchForm.t %}
                        <div>
                            <label for="{{ mTag.id_for_label }}">
                                {{ mTag.tag }}
                                <span>{{ mTag.choice_label }}</span>
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <input type="submit" id="search-btn" class="button_CCC" value="Submit">
        </form>
    </div>
    
{% endblock content %}

cccSite/mapViewer/templates/mapViewer/postTemplate.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  <style>
    body {
      background-color: white;
      font-family: Arial, sans-serif;
    }
    .post-list {
      list-style-type: none;
      padding: 0;
      max-width: 800px;
      margin: 0;
    }
    .post-item {
      background-color: white;
      border-radius: 30px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
      margin-bottom: 15px;
      padding: 15px;
    }
    .post-title {
      font-size: 1.25rem;
      margin-bottom: 5px;
      text-decoration: underline;
      color: black; /* Bulma primary color */
    }
    .post-title a {
      font-weight: bold;
      color: inherit;
      text-decoration: none;
    }
    .post-author {
      font-size: 0.9rem;
      color: black;
    }
    .post-content {
      margin-top: 10px;
      line-height: 1.6;
      font-size: 1rem;
    }
    hr {
        border: 0;
        height: 2px;
        background: black; /* Color of the line */
        margin: 20px 0; /* Space above and below the line */
    }
  </style>
</head>
<body>
    <ul class="post-list">
        <li class="post-item">
            <h2 class="post-title">
                <a href="/forum/{{forum.id}}/post/{{post.id}}">{{ post.title }}</a>
            <!-- This line should work. I don't know why it doesn't. The above line is my lazy replacement. -Roman -->
                {% comment %} <a href="{% url 'post_detail' forum.id post.id %}">{{ post.title }}</a> {% endcomment %}
            </h2>
            <p class="post-author">Posted by: {{ post.author }}</p>
            <div class="post-content">
                {{ post.content }}
            </div>
        </li>
        <!-- Repeat for other posts -->
    </ul>
</body>
</html>

cccSite/mapViewer/templates/mapViewer/viewForum.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
<title>Chesapeake Community Connect - Map</title>
<link rel="stylesheet" type="text/css" href="{% static 'mapViewer/viewforum.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">


<script src="{% static 'mapViewer/forumview.js' %}" defer></script>
{{forum.geoCode|json_script}}
{{ forumData|json_script:"forumData" }}



<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBN4e1y8ECEgsg_8U6xO02_2InU8G8I8cM&libraries=places&callback=initMap" defer></script>

{% endblock head %}


{% block content %}

{%if rank > 2%}
<a class="button_CCC" href="{{forum.get_admin_url}}">Manage Forum</a>
{%endif%}

{{msg}}

<div class = " is-pulled-right pb-10">  
    <div id="content" class="is-pulled-left">
        <button id="report-button" class="button mr-1 mt-1 fixed-button">Report Forum</button>
        <div id="report-form" style="display: none;">

        {% if not hasReported %}
        <form action="{{ request.build_absolute_uri }}" method="post">
            {% csrf_token %}
            <div id="report-field" class = "mt-3 has-text-dark is-shadowless" style="resize:none;">{{ form.as_p }}</div>
            <br>
            <input type="submit" value="Report" id="input-submit" class=" is-rounded is-size-6">
        </form>
        </div>
        {% else %}
        Your report has been received.
        {% endif %}
    </div>
</div>
<br>
<script>
    document.getElementById('report-button').addEventListener('click', function() {
        var reportForm = document.getElementById('report-form');
        if (reportForm.style.display === "none") {
            reportForm.style.display = "block";
        } else {
            reportForm.style.display = "none";
        }
    });
</script>

    
    <h1 class = "is-size-1 has-text-dark pl-3">{{ forum.title }}</h1>
    <p class = "is-size-5 has-text-dark pl-3">By <a class = "has-text-dark has-text-weight-semibold" href="{{forum.author.get_absolute_url}}">{{ forum.author }}</a></p>
    

    <!-- Google Map -->

    <!-- Slideshow HTML -->
    <div class = "container is-pulled-left " style = "min-width: 100%">
        <div class="transparent-box slideshow-container container  mx-6 is-pulled-left" >
            <!-- Slides -->
            <div class="mySlides fade">
                <div id="map">
                </div>
            </div>
            {% for item in files %}
            <div class="mySlides fade">
                <div class="image-container">
                    {% if item.format == 0 %}
                    <img src="{{ item.file.url }}" class="slide-image">
                    {% elif item.format == 1 %}
                    <video width="100%" controls>
                        <source src="{{ item.file.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                    {% elif item.format == 2 %}
                    <audio controls>
                        <source src="{{ item.file.url }}" type="audio/mpeg">
                        Your browser does not support the audio element.
                    </audio>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        
        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
</div>


    <div class = "has-text-dark is-size-5 ">
        <br>
        <p class = "pl-6">{{ forum.content }}</p>
        <br>
        <p class = "pl-6">Tags:</p>

        <ul style="list-style-type: none; padding-left: 20px;">
            {% for tag in forum.tags.all %}
            <li style="margin-bottom: 20px; padding-left: 20px; border: 1px solid #ddd; border-radius: 5px; display: flex; align-items: center; justify-content: flex-start; margin-right: 15px;">
                <!-- Display the tag name -->
                <span style="font-size: 1.1em; font-weight: bold; margin-right: 20px;">{{ tag.name }}</span>
                <br>
                <!-- Display the tag image -->
                {% if tag.image %}
                <img src="{{ tag.image.url }}" alt="{{ tag.name }}" style="width: 100px; height: 100px; object-fit: cover;">
                {% else %}
                <span>No image available</span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    

    <!-- this section was written by Quinnten Hatfield (qehatfield@smcm.edu) in FA24-->
    <!-- Purpose: Implements pagination of posts and displays them while viewing a Forum-->
    <!-- Note: If someone scrolls to fast, there may be an error where duplicate posts are shown accidentally-->
    <!-- Might be smart to add a better loading icon-->
    <hr class="ml-3">
        <h1 class="subtitle is-4 has-text-dark ml-6">Forum Posts</h1>
        <div id="forum-posts" class = "has-text-dark mx-6">
            <div id="posts-container">
                {% for post in posts %}
                    {% include 'mapViewer/postTemplate.html' with post=post%}
                {% endfor %}
            </div>
            
            <div id="loading-spinner" style="display: none;">Loading...</div> 
            
            <script>
                //JavaScript for pagination
                let currentPage = 1;
                let hasNextPage = true;
                let isFetching = false;
            
                //Purpose: use to determing when/if to load more posts, and then load them
                function loadMorePosts() {
                    //if statement so that the function is not used when there is no next page or when it is already fetching
                    if (!hasNextPage || isFetching) {
                        cosole.log("No more pages to load or is already fetching.");
                        return;
                    } 

                    //these were some logs to make sure it was working correctly
                    //console.log(`Fetching page ${currentPage + 1}`)
                    isFetching = true;
                    document.getElementById('loading-spinner').style.display = 'block';
                    currentPage += 1; //increment to next page
                    
                    //this section loads the data in from the backend
                    try {
                        fetch(`?page=${currentPage}`, {
                            headers: {
                                'X-Requested-With': 'XMLHttpRequest' 
                            }
                        })
                        .then(response => response.json())
                        .then(data => {
                            document.getElementById('loading-spinner').style.display = 'none';
                            const postsContainer = document.getElementById('posts-container');
                
                            data.posts.forEach(postHtml => {
                                const postElement = document.createElement('div');
                                postElement.innerHTML = postHtml;
                                postsContainer.appendChild(postElement);
                            });
                
                            hasNextPage = data.has_next;
                            //console.log(`Has next page: ${hasNextPage}`);
                        })
                        .catch(error => console.error('Error loading posts:', error));
                    } finally {
                        isFetching = false;
                    }
                }
                //on a scroll, try to load more posts
                window.addEventListener('scroll', () => {
                    if (window.innerHeight + window.scrollY >= document.body.offsetHeight - 300) { // if the - constant is closer to 0, must scroll further to load, but
                    //less chance of having duplicate posts. I think 300 is the best in between of amount of scroll and accuracy. 
                        loadMorePosts();
                    }
                });
            </script>
        </div>

{% endblock content %}