cccSite/Janitor/urls.py
from django.urls import path
from . import views

app_name = "Janitor"
urlpatterns = [
    path("", views.default, name="default"),
    path("messages/", views.contactList, name="messageList"),
    path("member/", views.memberList, name="memberList"),
    path("member/<int:want>/", views.member_manage, name="manage_user"),
    path("forum/", views.pendingForumList, name='forumList'),
    path('forum/<int:want>/', views.rev_forum, name='forumReview'),
    path('reports/', views.reportList, name="reportList"),
    path('tags/', views.tagList, name = "tagList"),
]

cccSite/account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("", views.default, name="default"),
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("authG/", views.authG, name="authG"),
    path("signout/", views.signout, name="signout"),
    path("manage/", views.manage, name='manage'),
    path("view/", views.account_list, name='account_list'),
    path("view/<want>/", views.account_view, name='account_view'),
    path("create/", views.make_forum, name="create_forum"),
    path("myforums/", views.my_forums, name='my_forums'),
    path("ajax/username_validation/", views.username_validation, name='username_validation'),
    path("ajax/email_validation/", views.email_validation, name='email_validation')
]

cccSite/boiler/urls.py
from django.urls import path
from . import views
#from mapViewer.views import viewMap

app_name = "boiler"
urlpatterns = [
   # path("", viewMap, name="viewMap"),
    path("about/", views.about, name="about"),
    path('help/', views.help, name='help'),
]

cccSite/cccSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mapViewer import views

app_name = 'mapViewer'

urlpatterns = [
    path("contribute/", include("account.urls")),
    path('DJadmin/', admin.site.urls),
    path("", include("mapViewer.urls")),
    path("", include("boiler.urls")),
    path("admin/", include("Janitor.urls")),
    path('forum/<int:want>/', views.forum_detail, name='forum_detail'),
] 
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

cccSite/cccSite/templates/base/base.html
<!-- 
    This is the base HTML file. The entire website loads from this file.
-->

<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'base/basestyle.css' %}">
    <script src="https://accounts.google.com/gsi/client" async></script>
    <script type="text/javascript" src="{% static 'base/jquery-3.7.1.min.js' %}"></script>
    {% block head%}{%endblock head%}
</head>
{%with rank=request.session.rank|default:0%}
<body>
    <!-- Navigation Bar  -->
    <header class="headerCCC">
        <nav>
            <ul> 
                <li><img src= "{%static 'base/assets/smcm-seal.png' %}" alt="SMCM Logo" id="smcm-logo"></li>
                <li><a class="nav-link" href="{% url 'mapViewer:default'%}" {%if '/about/' not in request.path and '/contact/' not in request.path and '/help/' not in request.path and '/contribute/' not in request.path and '/admin/' not in request.path%}style="background-color: #f3c10d; color: #00205c;"{%endif%}>Home</a></li>
                <li><a class="nav-link" href="{% url 'boiler:about'%}" {%if '/about/' in request.path%} style="background-color: #f3c10d; color: #00205c;"{%endif%}>About</a><!--<link rel="stylesheet" type="text/css" href="{% static 'base/aboutstyle.css' %}"></li> -->
                {% comment %} <li><a class="nav-link" href="{% url 'boiler:contact'%}" {%if '/contact/' in request.path%}style="background-color: #f3c10d; color: #00205c;" {%endif%}>Contact</a></li> {% endcomment %}
                <li><a class="nav-link" href="{% url 'boiler:help'%}" {%if '/help/' in request.path%}style="background-color: #f3c10d; color: #00205c;" {%endif%}>Help/Tutorial</a></li>
                <li><a class="nav-link" href="{%url 'account:default'%}" {%if '/contribute/' in request.path%}style="background-color: #f3c10d; color: #00205c;" {%endif%}>Contributors</a></li>
                {%if rank > 2 %}<li><a class="nav-link" href="{%url 'Janitor:default'%}" {%if '/admin/' in request.path%}style="background-color: #f3c10d; color: #00205c;" {%endif%}>Admin</a></li> {%endif%}
                {%if rank == 0%}<li style="margin-left: auto;">{% include "account/signup.html" %}</li>
                <li style="margin-right: 1em;">{% include "account/signin.html" %}</li>
                {% else %} {% with name=request.session.name|default:0 %}<li style="margin-left: auto; margin-right: 1em;"><a class="nav-link"  {% if '/contribute/' == request.path %}  style="background-color: #f3c10d; color: #00205c;" {% endif %} href={% url 'account:default' %}>{{ name }}</a></li> {% endwith %} {%endif%}
            </ul>
        </nav> 
    </header>
    <div id="g_id_onload" data-client_id="316865720473-94ccs1oka6ev4kmlv5ii261dirvjkja0.apps.googleusercontent.com"
          data-context="signin" data-ux_mode="popup" data-login_uri="{%url 'account:authG' %}"
          data-auto_prompt="false"></div>
   {% block content %} {%endblock content%}
    <!-- Footer -->
    <footer style="min-height: 350px;">
        <img src="{%static 'base/assets/smcm-logo.png' %}" alt="SMCM Logo" id="smcm-logo">
        &copy; 2025 SMCM Capstone Website
    </footer>
</body>
{%endwith%}
</html>